language: python
python:
  - "3.9"

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.9" COVERAGE="true"

install: make deps

script:
  make test
