language: python



notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"

install: source build_tools/travis/install.sh

script:
  nosetests
