language: python
python:
  - "3.6"
  - "3.9"

jobs:
  allow_failures:
    - python: 3.6
  fast_finish: true

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"

install: make deps

script:
  make test
